### PR TITLE
Scanhub UI/issue/33 login functionality

### PR DESCRIPTION
**Pull request by BenWilhelmUniklinikFreiburg**
Please continue work with the updated code to avoid future merge conflicts. Code was tested and should work. A default user needs to be added manually to the backend's database for now. Such a database entry is described in the readme and in defaultuser.txt of the scanhub backend. Frontend code to add users is still to do, but some backend functions for that exist and may be used with swagger ui.

### CODE REVIEW

**Comment by schote** [comment]
Please double-check the latest commit.
This PR already contains parts of the new template mechanism. Should we therefor also add all the other template related commits to this PR?
For the future I would suggest to always start from main and address only one feature to keep the history clean.

**Comment by BenWilhelmUniklinikFreiburg** [comment]
@schote sure, go ahead. Yes I would like to continue from main again, to avoid big merge conflicts.

**Comment by BenWilhelmUniklinikFreiburg** [comment]
User management should be pretty much complete now. Of course we might need to add the one or the other feature as we go forward, but it is usable now.

**Comment by BenWilhelmUniklinikFreiburg** [comment]
The issue https://github.com/brain-link/scanhub-ui/issues/33 could be closed with that.

**Review by jobehrens — APPROVED** [review]

**Pull request merged**
